wordpress_version: 4.8.1
wordpress_theme: twentysixteen

wordpress_wwwroot: /var/www/html
# wordpress_url: http://localhost/

wordpress_install_user: "{{ ansible_user }}"

wordpress_mysql_hostname: 127.0.0.1
wordpress_mysql_database: wordpress
wordpress_mysql_username: wordpress
wordpress_mysql_password: wordpress

wp_cli_home: /opt/wp-cli
