- name: "Ensure Xvfb"
  apt: name=xvfb
  become: yes

- name: 'Default display id'
  copy:
    content: |
      DISPLAY="${DISPLAY:-:{{ xvfb.display_id }}}"
      export DISPLAY
    dest: /etc/profile.d/xvfb.sh
  become: yes

- name: Ensure the directory for user systemd
  file: path="~/.config/systemd/user" state=directory
  become: no

- name: Ensure Xvfb Service
  copy:
    content: |
      [Unit]
      Description=Xvfb

      [Service]
      ExecStart=/usr/bin/Xvfb :{{ xvfb.display_id }} -ac

      [Install]
      WantedBy=default.target
    dest: ~/.config/systemd/user/xvfb.service
  notify: Restart xvfb service
  become: no

- name: Enable xvfb service
  systemd: name=xvfb user=yes enabled=yes state=started daemon_reload=yes
  become: no
