- name: 'VNC client server'
  apt: name=novnc

- name: 'vnc configuration for apache'
  copy:
    content: |
      <Location {{ vnc_web_client_path | default('/vnc') }}>
      RewriteEngine On
      RewriteRule / http://%{HTTP_HOST}:{{ 8900 + vnc_display_id }}/vnc_auto.html?password={{ vnc_passwd }}
      </Location>
    dest: /etc/apache2/conf-available/vnc-web-client.conf
  notify: Restart apache2

- name: 'enable vnc configuration'
  file:
    path: /etc/apache2/conf-enabled/vnc.conf
    state: link
    src: ../conf-available/vnc-web-client.conf
  notify: Restart apache2

- name: 'vnc web client service'
  template: src=vncwebclient dest=/usr/local/bin/ mode=a+x
  notify: Restart vncwebclient service

- name: Ensure the directory for user systemd
  file: path="~/.config/systemd/user" state=directory
  become: no

- name: Ensure VNC Web Client Service
  copy:
    content: |
      [Unit]
      Description=VNC Web Client

      [Service]
      ExecStart=/usr/local/bin/vncwebclient {{ vnc_display_id }}

      [Install]
      WantedBy=default.target
    dest: ~/.config/systemd/user/vncwebclient.service
  notify: Restart vncwebclient service
  become: no

- name: Enable vncwebclient service
  systemd: name=vncwebclient user=yes enabled=yes state=started
  become: no
